<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jason Pattison, ST558-651, SUM I 2024">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jason Pattison, ST558-651, SUM I 2024 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="diabetes-health-indicators---eda" class="level2">
<h2 class="anchored" data-anchor-id="diabetes-health-indicators---eda">Diabetes Health Indicators - EDA</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<section id="diabetes-binary-health-indicators" class="level4">
<h4 class="anchored" data-anchor-id="diabetes-binary-health-indicators">Diabetes Binary Health Indicators</h4>
<p>The diabetes binary health indicators file is a subset of 22 variables and 253,690 responses to questions asked of as part of the Behavioral Risk Factor Surveillance System (BHFSS) survey conducted in 2015.</p>
<p>The variables on the binary health indicators file are:</p>
<ul>
<li><p><strong>HasDiabetes</strong> is the target variable that we want to predict. It is a categorical variable with levels “0” for “No diabetes”, “1” for “Pre-diabetes”, and “2”” for “Diabetes”“. This variable has been renamed from the initial name of <strong>Diabetes_binary</strong>.</p></li>
<li><p><strong>HighBP</strong> is a categorical variable with levels “0” for “No high BP” and “1” for “High BP”.</p></li>
<li><p><strong>HighCholesterol</strong> is a categorical variable with levels “0” for “No High Cholesterol” and “1” for “High Cholesterol”. This variable has been renamed from the initial name of <strong>HighChol</strong>.</p></li>
<li><p><strong>CholesterolChecked</strong> is a categorical variable with levels “0” for “No cholesterol check in 5 years” and “1” for “Cholesterol check in 5 years”. This variable has been renamed from the initial name of <strong>CholCheck</strong>.</p></li>
<li><p><strong>BMI</strong> is a discrete numeric variable indicating the BMI level of the PT observed.</p></li>
<li><p><strong>Smoker</strong> is a factor variable with levels “0” for “No” and “Yes” as responses to the question “Have you smoked at least 100 cigarettes in your life?”.</p></li>
<li><p><strong>Stroke</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” as reponses to the question “Have you ever had or been told you had a stroke?”.</p></li>
<li><p><strong>HeartDiseaseorAttack</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Does the PT have coronary heart disease (CHD) or myocardial infraction (MI)?”.</p></li>
<li><p><strong>PhysActivity</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Not including your job, have you participated in physical activity in the past 30 days?”.</p></li>
<li><p><strong>ConsumesFruits</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Do you consume fruit 1 or more times per day?”. This variable has been renamed from the initial name of <strong>Fruits</strong>.</p></li>
<li><p><strong>ConsumesVeggies</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Do you consume vegetables 1 or more times per day?”. This variable has been renamed from the initial name of <strong>Veggies</strong>.</p></li>
<li><p><strong>HeavyAlcoholUse</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “How many drinks do you consume each week?”. Men responding to the question were placed in the “Yes” category if they consumed 14 or more alcoholic drinks in a week, otherwise they were placed in the “No” category. Women responding to the question were placed in the “Yes” category if they consumed 7 or more alcoholic drinks in a week, otherwise they were placed in the “No” category. This variable has been renamed from the initial name of <strong>HvyAlcoholConsump</strong>.</p></li>
<li><p><strong>HasHealthcare</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Do you have any kind of health care coverage?”. Responses stating the individual had health insurance or prepaid plans were grouped into the “Yes” category. This variable has been renamed from the initial name of <strong>AnyHealthcare</strong>.</p></li>
<li><p><strong>ExpensiveTreatment</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?”. This variable has been renamed from the initial name of <strong>NoDocbcCost</strong>.</p></li>
<li><p><strong>GeneralHealth</strong> is a categorical variable with response levels “1” for “Excellent”, “2” for “Very Good”, “3 for”Good”, “4” for “Fair”, and “5” for “Poor” to the question “Would you say your general health is…?”. This variable has been renamed from the initial name of <strong>GenHlth</strong>.</p></li>
<li><p><strong>BadMentalHealth</strong> is a categorical variable with levels “0” through “30” as responses to the question “Over the last 30 days, how many did you experience poor mental health”. Given the thirty different possible responses, it may be suitable to treat <strong>BadMentalHealth</strong> as a numeric variable. This variable has been renamed from the initial name of <strong>MentHlth</strong>.</p></li>
<li><p><strong>BadPhysicalHealth</strong> is a categorical variable with levels “0” through “30” as responses to the question “Over the last 30 days, how many did you experience having physical illness or an injury?”. Given the thirty different possible responses, it may be suitable to treat <strong>BadPhysicalHealth</strong> as a numeric variable. This variable has been renamed from the initial name of <strong>PhysHlth</strong>.</p></li>
<li><p><strong>DifficultyWalking</strong> is a categorical variable with levels “0” for “No” and “1” for “Yes” to the question “Do you have serious difficulty walking or climbing stairs?”.</p></li>
<li><p><strong>Sex</strong> is a categorical variable with levels “0” for “Female” and “1” for “Male” to the question “What is your Sex?”.</p></li>
<li><p><strong>Age</strong> is a categorical variable with levels ranging from “1” for “18-24” to “13” for “80 or Older” to the question “What is your age?”. The response were binned together in 5year groups with the exception of groups 1 and 13. Group 1 was expanded to account for PTs that were 18yo or 19yo. Group 13 was created to account for anyone who was 80yo or older.</p></li>
<li><p><strong>Education</strong> is a categorical variable with levels “1” through “8” as responses to the question “What is the highest grade or year of school you completed?”. The response levels are “1” for “Never attended school or only Kindergarten”, “2” for “Grades 1 through 8 (Elementary)”, “3” for “Grades 9 through 11 (Some high school)”, “4” for “Grade 12 or GED (High school graduate)”, “5” for “College 1 year to 3 years (Some college or technical school)”, and “6” for “College 4 years or more (College graduate)”.</p></li>
<li><p><strong>Income</strong> is a categorical variable with levels “1” through “8” as reponses to the question “Is your annual income from all sources:?”. The response levels are “1” for “Less than $10,000”, “2” for “Less than $15,000”, “3” for “Less than $20,000”, “4” for “Less than $25,000”, “5” for “Less than $35,000”, “6” for “Less than $50,000”, “7” for “Less than $75,000”, and “8” for “$75,000 or more”.</p></li>
</ul>
</section>
<section id="purpose-and-goal" class="level4">
<h4 class="anchored" data-anchor-id="purpose-and-goal">Purpose and goal</h4>
<p>The purpose of the Exploratory Data Analysis (EDA) is to summarize the information from the twenty-one predictor variables with respect to <strong>Diabetes_binary</strong> and determine if any relationships exist.</p>
<p>The goal of the EDA is to identify the variables having relationships with <strong>Diabetes_binary</strong> that are also suitable for prediction modeling. We will use these variables to generate different prediction model types and determine one that has the highest rate of success at predicting if someone has diabetes or not.</p>
</section>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>Before we read-in the data set, we need to establish a library required to use the functions required for summary analysis in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will read-in the data using a relative path to the folder where the data file is stored.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use a relative path to import the data. </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>diabetes_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./FinalProjectRawData/diabetes_binary_health_indicators_BRFSS2015.csv"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>diabetes_df <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(diabetes_df)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>diabetes_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 253,680 × 22
   Diabetes_binary HighBP HighChol CholCheck   BMI Smoker Stroke
             &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1               0      1        1         1    40      1      0
 2               0      0        0         0    25      1      0
 3               0      1        1         1    28      0      0
 4               0      1        0         1    27      0      0
 5               0      1        1         1    24      0      0
 6               0      1        1         1    25      1      0
 7               0      1        0         1    30      1      0
 8               0      1        1         1    25      1      0
 9               1      1        1         1    30      1      0
10               0      0        0         1    24      0      0
# ℹ 253,670 more rows
# ℹ 15 more variables: HeartDiseaseorAttack &lt;dbl&gt;, PhysActivity &lt;dbl&gt;,
#   Fruits &lt;dbl&gt;, Veggies &lt;dbl&gt;, HvyAlcoholConsump &lt;dbl&gt;, AnyHealthcare &lt;dbl&gt;,
#   NoDocbcCost &lt;dbl&gt;, GenHlth &lt;dbl&gt;, MentHlth &lt;dbl&gt;, PhysHlth &lt;dbl&gt;,
#   DiffWalk &lt;dbl&gt;, Sex &lt;dbl&gt;, Age &lt;dbl&gt;, Education &lt;dbl&gt;, Income &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We will then check for missingness,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(<span class="st">"Number of missing values in data set"</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(diabetes_df)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Number of missing values in data set`
[1] 0</code></pre>
</div>
</div>
<p>We see that there are no missing values throughout the data set so we can proceed with converting the categorical variables to factors and provide meaningful names to variables if needed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert variables to factors, replace with meaningful names</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>diabetes_df <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"HasDiabetes"</span> <span class="ot">=</span> Diabetes_binary, </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>         <span class="st">"HighCholesterol"</span> <span class="ot">=</span> HighChol, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>         <span class="st">"CholesterolChecked"</span> <span class="ot">=</span> CholCheck, </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="st">"ConsumesFruits"</span> <span class="ot">=</span> Fruits, </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>         <span class="st">"ConsumesVeggies"</span> <span class="ot">=</span> Veggies, </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>         <span class="st">"HeavyAlcoholUse"</span> <span class="ot">=</span> HvyAlcoholConsump,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>         <span class="st">"HasHealthcare"</span> <span class="ot">=</span> AnyHealthcare,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">"ExpensiveTreatment"</span> <span class="ot">=</span> NoDocbcCost,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>         <span class="st">"GeneralHealth"</span> <span class="ot">=</span> GenHlth,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>         <span class="st">"BadMentalHealth"</span> <span class="ot">=</span> MentHlth,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>         <span class="st">"BadPhysicalHealth"</span> <span class="ot">=</span> PhysHlth,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>         <span class="st">"DifficultyWalking"</span> <span class="ot">=</span> DiffWalk) <span class="sc">|&gt;</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">6</span><span class="sc">:</span><span class="dv">15</span>, <span class="dv">18</span><span class="sc">:</span><span class="dv">22</span>), as.factor))</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(diabetes_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [253,680 × 22] (S3: tbl_df/tbl/data.frame)
 $ HasDiabetes         : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 2 1 ...
 $ HighBP              : Factor w/ 2 levels "0","1": 2 1 2 2 2 2 2 2 2 1 ...
 $ HighCholesterol     : Factor w/ 2 levels "0","1": 2 1 2 1 2 2 1 2 2 1 ...
 $ CholesterolChecked  : Factor w/ 2 levels "0","1": 2 1 2 2 2 2 2 2 2 2 ...
 $ BMI                 : num [1:253680] 40 25 28 27 24 25 30 25 30 24 ...
 $ Smoker              : Factor w/ 2 levels "0","1": 2 2 1 1 1 2 2 2 2 1 ...
 $ Stroke              : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 1 1 ...
 $ HeartDiseaseorAttack: Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 2 1 ...
 $ PhysActivity        : Factor w/ 2 levels "0","1": 1 2 1 2 2 2 1 2 1 1 ...
 $ ConsumesFruits      : Factor w/ 2 levels "0","1": 1 1 2 2 2 2 1 1 2 1 ...
 $ ConsumesVeggies     : Factor w/ 2 levels "0","1": 2 1 1 2 2 2 1 2 2 2 ...
 $ HeavyAlcoholUse     : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 1 1 ...
 $ HasHealthcare       : Factor w/ 2 levels "0","1": 2 1 2 2 2 2 2 2 2 2 ...
 $ ExpensiveTreatment  : Factor w/ 2 levels "0","1": 1 2 2 1 1 1 1 1 1 1 ...
 $ GeneralHealth       : Factor w/ 5 levels "1","2","3","4",..: 5 3 5 2 2 2 3 3 5 2 ...
 $ BadMentalHealth     : num [1:253680] 18 0 30 0 3 0 0 0 30 0 ...
 $ BadPhysicalHealth   : num [1:253680] 15 0 30 0 0 2 14 0 30 0 ...
 $ DifficultyWalking   : Factor w/ 2 levels "0","1": 2 1 2 1 1 1 1 2 2 1 ...
 $ Sex                 : Factor w/ 2 levels "0","1": 1 1 1 1 1 2 1 1 1 2 ...
 $ Age                 : Factor w/ 13 levels "1","2","3","4",..: 9 7 9 11 11 10 9 11 9 8 ...
 $ Education           : Factor w/ 6 levels "1","2","3","4",..: 4 6 4 3 5 6 6 4 5 4 ...
 $ Income              : Factor w/ 8 levels "1","2","3","4",..: 3 1 8 6 4 8 7 4 1 3 ...</code></pre>
</div>
</div>
<p>Review of our data frame structure shows that we have successfully renamed our variables and converted the categorical variables to factors. It is important to note that while <strong>BadMentalHealth</strong> and <strong>BadPhysicalHealth</strong> are categorical responses in the survey, the responses are discrete over a range of possible entries (1 to 30) makes them candidates for numeric analysis.</p>
<p>Next we will generate a summary of the variables to provide insight on what we can expect to see during our EDA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Diabetes Data Frame Variables"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Diabetes Data Frame Variables`
 HasDiabetes HighBP     HighCholesterol CholesterolChecked      BMI       
 0:218334    0:144851   0:146089        0:  9470           Min.   :12.00  
 1: 35346    1:108829   1:107591        1:244210           1st Qu.:24.00  
                                                           Median :27.00  
                                                           Mean   :28.38  
                                                           3rd Qu.:31.00  
                                                           Max.   :98.00  
                                                                          
 Smoker     Stroke     HeartDiseaseorAttack PhysActivity ConsumesFruits
 0:141257   0:243388   0:229787             0: 61760     0: 92782      
 1:112423   1: 10292   1: 23893             1:191920     1:160898      
                                                                       
                                                                       
                                                                       
                                                                       
                                                                       
 ConsumesVeggies HeavyAlcoholUse HasHealthcare ExpensiveTreatment GeneralHealth
 0: 47839        0:239424        0: 12417      0:232326           1:45299      
 1:205841        1: 14256        1:241263      1: 21354           2:89084      
                                                                  3:75646      
                                                                  4:31570      
                                                                  5:12081      
                                                                               
                                                                               
 BadMentalHealth  BadPhysicalHealth DifficultyWalking Sex       
 Min.   : 0.000   Min.   : 0.000    0:211005          0:141974  
 1st Qu.: 0.000   1st Qu.: 0.000    1: 42675          1:111706  
 Median : 0.000   Median : 0.000                                
 Mean   : 3.185   Mean   : 4.242                                
 3rd Qu.: 2.000   3rd Qu.: 3.000                                
 Max.   :30.000   Max.   :30.000                                
                                                                
      Age        Education      Income     
 9      :33244   1:   174   8      :90385  
 10     :32194   2:  4043   7      :43219  
 8      :30832   3:  9478   6      :36470  
 7      :26314   4: 62750   5      :25883  
 11     :23533   5: 69910   4      :20135  
 6      :19819   6:107325   3      :15994  
 (Other):87744              (Other):21594  </code></pre>
</div>
</div>
<p>Reeview of the data set summary shows that <strong>BMI</strong> appears to be centered with outliers that need investigated for removal. With median values of “0” over a range of 1-30, both <strong>BadMentalHealth</strong> and <strong>BadPhysicalHealth</strong> have a high tendency response of “0” in the survey. <strong>HighBP</strong>, <strong>HighCholesterol</strong>, <strong>Smoker</strong>, <strong>GeneralHealth</strong>, <strong>Sex</strong> and <strong>Age</strong> each appear to have response ratios near 1:1. The remaining binary variables of <strong>CholesterolChecked</strong>, <strong>Stroke</strong>, <strong>HeartDiseaseorAttack</strong>, <strong>PhysActivity</strong>, <strong>ConsumesFruits</strong>, <strong>ConsumesVeggies</strong>, <strong>HeavyAlcoholUse</strong>, <strong>HasHealthcare</strong>, <strong>ExpensiveTreatment</strong>, and <strong>DifficultyWalking</strong> each heavily favor one response over the other. The variables of <strong>Education</strong> and <strong>Income</strong> both show an increase in responses as the category range values increase.</p>
</section>
<section id="summarizations" class="level3">
<h3 class="anchored" data-anchor-id="summarizations">Summarizations</h3>
<p>The first variable we will investigate is <strong>BMI</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of BMI"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>BMI)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of BMI`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  12.00   24.00   27.00   28.38   31.00   98.00 </code></pre>
</div>
</div>
<p>that the data has a Q1 value of 24, Q3 value of 31, Median of 27, and Mean of 28.38. This tells us the data is tightly grouped together with BMI values of less than 13.5 and greater than 41.5 as outliers. These outliers include our Min of 12 and Max of 98. A histogram of <strong>BMI</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>BMI_histogram <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes_df, <span class="fu">aes</span>(BMI)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth=</span><span class="dv">1</span>, <span class="at">fill=</span><span class="st">"#CC0000"</span>, <span class="at">color=</span><span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Histogram of BMI"</span>, <span class="at">y=</span><span class="st">"Density (# of PTs)"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="fu">mean</span>(diabetes_df<span class="sc">$</span>BMI), <span class="at">sd=</span><span class="fu">sd</span>(diabetes_df<span class="sc">$</span>BMI))) </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>BMI_histogram</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Histogram of BMI-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the data follows a generally normal distribution with some skewness to the right. The histogram also visually confirms there are outleirs in the <strong>BMI</strong> ranges of 12-13 and 50-98.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lowrange <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes_df<span class="sc">$</span>BMI <span class="sc">&lt;</span> <span class="fl">13.5</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>highrange <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes_df<span class="sc">$</span>BMI <span class="sc">&gt;</span> <span class="fl">41.5</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>BMIoutliers <span class="ot">&lt;-</span><span class="fu">sum</span>(lowrange, highrange)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Number of BMI Oultiers"</span><span class="ot">=</span>BMIoutliers))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Number of BMI Oultiers`
[1] 9847</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"BMI Outlier portion of data set"</span><span class="ot">=</span>BMIoutliers<span class="sc">/</span><span class="fu">nrow</span>(diabetes_df)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`BMI Outlier portion of data set`
[1] 0.03881662</code></pre>
</div>
</div>
<p>We identified there are total of 9847 observation that are outliers when using 1.5 the IQR as our defining statistic. This accounts for over 3.88% of the data set, which is a higher than we’re willing to remove. Because the histogram shows there is close to a 0% probability of entries starting near a <strong>BMI</strong> of 50,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>lowrange <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes_df<span class="sc">$</span>BMI <span class="sc">&lt;</span> <span class="fl">13.5</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>highrange <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes_df<span class="sc">$</span>BMI <span class="sc">&gt;</span> <span class="dv">50</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>BMIoutliers <span class="ot">&lt;-</span><span class="fu">sum</span>(lowrange, highrange)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Number of BMI Oultiers"</span><span class="ot">=</span>BMIoutliers))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Number of BMI Oultiers`
[1] 2202</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"BMI Outlier portion of data set"</span><span class="ot">=</span>BMIoutliers<span class="sc">/</span><span class="fu">nrow</span>(diabetes_df)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`BMI Outlier portion of data set`
[1] 0.008680227</code></pre>
</div>
</div>
<p>we udpated the parametrs and found there to be 2202 outlier observations which account for less than 1% of the data set. It would be reasonable to remove these observations from the data set before prediction model training.</p>
<p>Removing the outliers then splitting the <strong>BMI</strong> histogram with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>diabetes_df <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(BMI <span class="sc">&gt;=</span> <span class="fl">13.5</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(BMI <span class="sc">&lt;=</span> <span class="dv">50</span> )</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>BMI_by_histplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes_df, <span class="fu">aes</span>(BMI)) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth=</span><span class="dv">1</span>, <span class="at">fill=</span><span class="st">"#CC0000"</span>, <span class="at">color=</span><span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Histogram of BMI by HasDiabetes"</span>, <span class="at">y=</span><span class="st">"Density (# of PTs)"</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun=</span>dnorm, <span class="at">args=</span><span class="fu">list</span>(<span class="at">mean=</span><span class="fu">mean</span>(diabetes_df<span class="sc">$</span>BMI), <span class="at">sd=</span><span class="fu">sd</span>(diabetes_df<span class="sc">$</span>BMI))) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>HasDiabetes)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>BMI_by_histplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Histogram of BMI with respect to HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the distribution of observations in the “No” <strong>HasDiabetes</strong> group has a center near a BMI of 25 while the “Yes” <strong>HasDiabetes</strong> group has a center near a BMI of 30. This change of <strong>BMI</strong> density distributions between the <strong>HasDiabetes</strong> groups indicates that <strong>BMI</strong> appears to be a suitable variable for prediction modeling.</p>
<p>The next variable we will investigate is <strong>HighPB</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of HighBP"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>HighBP)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of HighBP`
     0      1 
143994 107484 </code></pre>
</div>
</div>
<p>there are greater number of observations of PTs not having high blood pressure to those that do in a ratio of approximately 7:5. This is fairly close to being 1:1, so any differences between the <strong>HasDiabetes</strong> categories would be due to interactions between the variables.</p>
<p>Using a bar plot to observe <strong>HighBP</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>HighBP_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, HighBP) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>HighPB_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(HighBP_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>HighBP)) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bar Plot of HighBP by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span><span class="st">"# of PTs"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>HighPB_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/HighBP by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the majority of PTs with diabetes have high blood pressure while the majority of PTs without diabetes do not have high blood pressure. The observations in the “No” <strong>HasDiabetes</strong> category have a “No” to “Yes” <strong>HighBP</strong> ratio of approximately 7:4 (near 2:1). The observations in the “Yes” <strong>HasDiabetes</strong> category have a “No” to “Yes” <strong>HighBP</strong> ratio of approximately 4:13 (near 1:3). This flip in ratios between the <strong>HasDiabetes</strong> groups suggests that there is a relationship between <strong>HasDiabetes</strong> and <strong>HighBP</strong> where a PT with high blood pressure will also have diabetes.</p>
<p>The next variable that we will investigate is <strong>HighCholesterol</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of HighCholesterol"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>HighCholesterol)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of HighCholesterol`
     0      1 
144867 106611 </code></pre>
</div>
</div>
<p>there is approximately a 14:11 “No” to “Yes” ratio of <strong>HighCholesterol</strong> observations. This distribution is fairly close to being 1:1, so any differences between the <strong>HasDiabetes</strong> categories would be due to interactions between the variables.</p>
<p>Using a bar plot to observe <strong>HighCholesterol</strong> with respect to <strong>HasDiabetes</strong> we see</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>HighCholesterol_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, HighCholesterol) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>HighCholesterol_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(HighCholesterol_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>HighCholesterol)) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of HighCholesterol by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>HighCholesterol_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar Plot HighCholesterol by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the ratios change between the <strong>HasDiabetes</strong> groups. While the ratios favor low cholesterol in the group without diabetes, they favor high cholesterol levels in the group with diabetes. There is approximately a 13:8 (nears 2:1) ratio of “No” to “Yes” <strong>HighCholesterol</strong> responses in the “No” <strong>HasDiabetes</strong> group. There is approximately a 11:23 (nears 1:2) ratio of “No” to “Yes” <strong>HighCholesterol</strong> responses in the “Yes” <strong>HasDiabetes</strong> group. The shift in ratios between the groups trending towards PTs with diabetes having high cholesterol suggests that there is a relationship between <strong>HasDiabetes</strong> and <strong>HighCholesterol</strong> where someone with high cholesterol will also have diabetes.</p>
<p>The next variable we will investigate is <strong>CholesterolChecked</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of CholesterolChecked"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>CholesterolChecked)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of CholesterolChecked`
     0      1 
  9404 242074 </code></pre>
</div>
</div>
<p>that the overwhelming majority of PTs had their cholesterol checked at a ratio of 9:242 (nears 1:27) when compared to those who did not. Any differences between the <strong>HasDiabetes</strong> groups may be heavily influenced by the number of observations in each group more than the interaction between the variables. Review of a bar plot of <strong>CholesterolChecked</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>CholesterolChecked_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, CholesterolChecked) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>CholesterolChecked_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(CholesterolChecked_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>CholesterolChecked)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of CholesterolChecked by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>CholesterolChecked_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot of CholesterolChecked by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the group of “Yes” <strong>CholesterolChecked</strong> responses dominates both categories of <strong>HasDiabetes</strong>. The “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>CholesterolChecked</strong> ratio of approximately 9:208 (nears 1:23). The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>CholesterolChecked</strong> ratio of approximately 1:172. This information suggests that there is a relationship between the variables where someone with diabetes has a high probability of having their cholesteroal checked every five years, which is not what we’re trying to predict. <strong>CholesterolChecked</strong> does not appear to be a good variable for use in prediction modeling.</p>
<p>The next variable we’re going to analyze is <strong>Smoker</strong>. Review of the variable summary shows that</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Smoker"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>Smoker)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Smoker`
     0      1 
139967 111511 </code></pre>
</div>
</div>
<p>the ratio of smokers to non-smokers in the study is approximately 14:11. This is distribution between the groups is fairly close to a 1:1 distribution. Any differences between the <strong>HasDiabetes</strong> groups will be due to interactions between the two variables. Reviewing the bar plot of <strong>Smoker</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Smoker_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, Smoker) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>Smoker_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Smoker_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>Smoker)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of Smoker by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>Smoker_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot Smoker by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>shows that the “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>Smoker</strong> distribution of approximately 62:47 which is closer to a 1:1 distribution than a 2:1 distribution. The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>Smoker</strong> distribution of approximately 17:18 which also nears a 1:1 distribution. While the ratios shifts indicate that smokers have a higher likelihood of having diabetes than non smokers, neither <strong>Smoker</strong> group separates itself from the variable in both <strong>HasDiabetes</strong> categories. <strong>Smoker</strong> is not a suitable variable for inclusion in our prediction model.</p>
<p>The next variable we are going to analyze is <strong>Stroke</strong>. Review of the variable summary shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Stroke"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>Stroke)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Stroke`
     0      1 
241295  10183 </code></pre>
</div>
</div>
<p>that <strong>Stroke</strong> has a 24:1 “No” to “Yes” ratio. This suggests that any differences between the <strong>HasDiabetes</strong> groups may be heavily influenced by the number of observations in each group more than the interaction between the variables. Review of a bar plot for <strong>Stroke</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>Stroke_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, Stroke) <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>Stroke_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Stroke_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>Stroke)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of Stroke by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>Stroke_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the <strong>Stroke</strong> “No” group is prominent in both groups of <strong>HasDiabetes</strong>. The “No” <strong>HasDiabetes</strong> group has a “No to”Yes” <strong>Stroke</strong> ratio of approximately 211:7 which is close to 30:1. The “Yes” <strong>HasDiabetes</strong> group has a “No to”Yes” <strong>Stroke</strong> ratio of approximately 32:3 which is close to 11:1. While still favoring the “No” <strong>Stroke</strong> group, the reduction in ratios indicates that there is a relationship between <strong>Stroke</strong> and <strong>HasDiabetes</strong>. However, the relationship appears to be where someone who had a stroke is likely to also have diabetes, but not someone who has diabetes is likely to have had a stroke. <strong>Stroke</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variable we are going to analyze is <strong>HeartDisesaseorAttack</strong>. Summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of HeartDiseaseorAttack"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>HeartDiseaseorAttack)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of HeartDiseaseorAttack`
     0      1 
227838  23640 </code></pre>
</div>
</div>
<p>that the ratio between the “No” and “Yes” <strong>HeartDiseaseorAttack</strong> groups is approximately 23:2 which is slightly larger than 11:1. Review of a bar plot for <strong>HeartDiseaseorAttack</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>HeartDiseaseorAttack_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, HeartDiseaseorAttack) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>HeartDiseaseorAttack_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(HeartDiseaseorAttack_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>HeartDiseaseorAttack)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of HeartDiseaseorAttack by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>HeartDiseaseorAttack_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot of HeartDiseaseorAttack by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>shows that the “No” <strong>HeartDiseaseorAttack</strong> group is noticably larger than the “Yes” group for each category of <strong>HasDiabetes</strong>. The “No” <strong>HeartDisease</strong> group has a “No” to “Yes” <strong>HeartDiseaseorAttack</strong> ratio of approximately 10:1. The “Yes” <strong>HeartDisease</strong> group has a “No” to “Yes” <strong>HeartDiseaseorAttack</strong> ratio of 27:7 which nears 4:1. The ratio change between the <strong>HasDiabetes</strong> groups suggests that there is a relationship between the variables. However, this relationship appears to be one where someone having diabetes can be used to predict if they have heart disease or have experienced a heart attack, which is not what we’re trying to predict. <strong>HeartDiseaseorAttack</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variable we will summarize is <strong>PhysActivity</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of PhysicalActivity"</span><span class="ot">=</span> <span class="fu">summary</span>(diabetes_df<span class="sc">$</span>PhysActivity)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of PhysicalActivity`
     0      1 
 60722 190756 </code></pre>
</div>
</div>
<p>the ratio of “No” to “Yes” responses is approximately 6:19 which is slightly less than 1:3. This suggests that differences between the <strong>HasDiabetes</strong> groups may be influenced by the number of “Yes” <strong>PhysActivity</strong> observations. Review of a bar plot of <strong>PhysActivity</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>PhysActivity_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, PhysActivity) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>PhysActivity_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(PhysActivity_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>PhysActivity)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of PhysActivity by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>PhysActivity_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot of PhysActivity by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>PhysActivity</strong> is greater in both <strong>HasDiabetes</strong> groups. The “No” <strong>HeartDisease</strong> group has a “No” to “Yes” <strong>PhysActivity</strong> ratio of approximately 5:17 which is slightly less than 1:3. The “Yes” <strong>HeartDisease</strong> group has a “No” to “Yes” <strong>PhysActivity</strong> ratio of approximately 13:22 which is slightly greater than 1:2. This change in ratios shows that there is a relationship between the variables. The relationship appears to be one where someone having diabetes can be used to predict if they participate in physical activity or not, which is not what we’re trying to predict. <strong>PhysActivity</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variable we’re going to summarize is <strong>ConsumesFruits</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of ConsumesFruits"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>ConsumesFruits)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of ConsumesFruits`
     0      1 
 91734 159744 </code></pre>
</div>
</div>
<p>that <strong>ConsumesFruits</strong> has a “No” to “Yes” ratio of approximately 9:16, which is slightly greater than a 1:2 distribution. Review of a bar graph of <strong>ConsumesFruits</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>ConsumesFruits_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, ConsumesFruits) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>ConsumesFruits_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ConsumesFruits_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>ConsumesFruits)) <span class="sc">+</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of ConsumesFruits by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>ConsumesFruits_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot of ConsumesFruits by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that both groups of <strong>HasDiabetes</strong> have a greater number of “Yes” <strong>ConsumesFruits</strong> observations. The “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>ConsumesFruits</strong> ratio of approximately 8:14 which is slightly greater than 1:2. The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>ConsumesFruits</strong> ratio of approximately 15:21 which is slightly greater than 2:3. This change in ratios shows that there is a relationship between the variables. However, the relationship appears to be one where someone having diabetes can be used to predict if they eat fruits or not, which is not what we’re tyring to predict. <strong>ConsumesFruits</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variabel we’re going to summarize is **ConsumesVeggies*. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of ConsumesVeggies"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>ConsumesVeggies)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of ConsumesVeggies`
     0      1 
 47284 204194 </code></pre>
</div>
</div>
<p>that the proporiton of “No” to “Yes” responses is approximately 5:21 which is slightly less than 1:4. Review of a bar plot of <strong>ConsumesVeggies</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>ConsumesVeggies_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, ConsumesVeggies) <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>ConsumesVeggies_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ConsumesVeggies_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>ConsumesVeggies)) <span class="sc">+</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of ConsumesVeggies by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>ConsumesVeggies_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot of ConsumesVeggies by HasDiabetes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the “Yes” <strong>ConsumesVeggies</strong> observations are substantially greater in both categories of <strong>HasDiabetes</strong>. The “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>ConsumesVeggies</strong> ratio of approximately 2:9 which is slightly less than 1:4. The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>ConsumesVeggies</strong> ratio of approximately 1:3. The change in ratios between the <strong>HasDiabetes</strong> groups shows that there is a relationship between the variables. However, the relationship appears to be one where someone having diabetes can be used to predict if they eat vegetables or not, which is not what we’re trying to predict. <strong>ConsumesVeggies</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variable we’re going to summarize is <strong>HeavyAlcoholUse</strong>. Review of the variable summary information shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of HeavyAlcoholUse"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>HeavyAlcoholUse)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of HeavyAlcoholUse`
     0      1 
237283  14195 </code></pre>
</div>
</div>
<p>shows that the ratio of “No” to “Yes” responses is approximately 24:1. This suggests that any differences between the <strong>HasDiabetes</strong> groups may be influenced by the number of observations. Reviewing the bar plot of <strong>HeavyAlcoholUse</strong> with respect to **HeartDisease* shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>HeavyAlcoholUse_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, HeavyAlcoholUse) <span class="sc">|&gt;</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>HeavyAlcoholUse_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(HeavyAlcoholUse_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>HeavyAlcoholUse)) <span class="sc">+</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of HeavyAlcoholUse by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>HeavyAlcoholUse_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/Bar plot of HeavyAlcoholUse by HeartDisease-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the “No” <strong>HeavyAlcoholUse</strong> responses constitute the majority of observations in both <strong>HasDiabetes</strong> groups. The “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>HeavyAlcoholUse</strong> ratio of approximately 205:13 which reduces close to 16:1. The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>HeavyAlcoholUse</strong> ratio of approximately 345:8 which reduces close to 43:1. The change in ratios shows that there is a relationship between the variables. However, the relationship appears to be one where someone having diabetes can be used to predict if they consume alcohol heavily, which is not what we’re trying to predict. <strong>HeavyAlcoholUse</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variable we’re going to summarize is <strong>HasHealthcare</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of HasHealthcare"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>HasHealthcare)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of HasHealthcare`
     0      1 
 12246 239232 </code></pre>
</div>
</div>
<p>shows that the ratio of “No” to “Yes” observations is approximately 12:241 which is close to a 1:20 ratio. This is suggestive that any differences between the <strong>HasDiabetes</strong> categories may be heavily influenced by the number of responses in each. Reviewing the bar chart of <strong>HasHealthcare</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>HasHealthcare_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, HasHealthcare) <span class="sc">|&gt;</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>HasHealthcare_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(HasHealthcare_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>HasHealthcare)) <span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of HasHealthcare by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) </span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>HasHealthcare_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>the “Yes” <strong>HasHealthcare</strong> observations are substantially higher than the “No” responses for both categories of **HasDiabetes*. The “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>HasHealthcare</strong> ratio of approximately 11:207 which reduces close to 1:19. The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>HasHealthcare</strong> ratio of approximately 14:339 which reduces close to 1:24. The ratios in both groups of <strong>HasDiabetes</strong> do not differ much from the overall <strong>HasHealthcare</strong> variable ratio of 1:20. <strong>HasHealthcare</strong> does not appear to be suitable for inclusion in the prediction model.</p>
<p>The next variable we’re going to summarize is <strong>ExpensiveTreatment</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of ExpensiveTreatment"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>ExpensiveTreatment)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of ExpensiveTreatment`
     0      1 
230457  21021 </code></pre>
</div>
</div>
<p>that the ration of “No” to “Yes” observations is approximately 232:21 which reduces near 11:1. This is suggestive that any differences between the <strong>HasDiabetes</strong> categories may be heavily influenced by the number of repsonses in each. Reviwing the bar chart of <strong>ExpensiveTreatment</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>ExpensiveTreatment_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, ExpensiveTreatment) <span class="sc">|&gt;</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>ExpensiveTreatment_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ExpensiveTreatment_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>ExpensiveTreatment)) <span class="sc">+</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of ExpensiveTreatment by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>ExpensiveTreatment_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>the “No” observations are substantially greater than the “Yes” responses for both categories of <strong>HasDiabetes</strong>. The “No” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>ExpensiveTreatment</strong> ratio of approximately 201:17 which reduces close to 12:1. The “Yes” <strong>HasDiabetes</strong> group has a “No” to “Yes” <strong>ExpensiveTreatment</strong> ratio of approximately 316:37 which reduces close to 9:1. There appears to be a relationship between the variables where someone with diabetes has a greater likelihood of not seeking treatment due to the cost, but that is not what we’re trying to predict. <strong>ExpensiveTreatment</strong> does not appear to be suitbale for inclusion in the prediciton model.</p>
<p>The next variable we’re going to summarize is <strong>GeneralHealth</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of GeneralHealth"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>GeneralHealth)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of GeneralHealth`
    1     2     3     4     5 
45159 88704 74967 30900 11748 </code></pre>
</div>
</div>
<p>shows that the majority of patients reported being in “Excellent” to “Good” health. Reviewing the bar chart of <strong>GeneralHealth</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>GeneralHealth_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, GeneralHealth) <span class="sc">|&gt;</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>GeneralHealth_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(GeneralHealth_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>GeneralHealth)) <span class="sc">+</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of GeneralHealth by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) </span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>GeneralHealth_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that there is a shift in the reporting tendencies between the <strong>HasDiabetes</strong> categories. The “No” <strong>HasDiabetes</strong> group has a central tendency of “Very Good” followed by “Good” <strong>GeneralHealth</strong> responses while the “Yes” <strong>HasDiabetes</strong> group has a central tendency of “Good” followed by “Fair” <strong>GeneralHealth</strong> responses</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>NoDiabetes_high_three <span class="ot">&lt;-</span> <span class="fu">sum</span>(GeneralHealth_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])<span class="sc">/</span><span class="fu">sum</span>(GeneralHealth_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>NoDiabetes_fourth <span class="ot">&lt;-</span> GeneralHealth_by<span class="sc">$</span>count[<span class="dv">4</span>]<span class="sc">/</span><span class="fu">sum</span>(GeneralHealth_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>YesDiabetes_high_three <span class="ot">&lt;-</span> <span class="fu">sum</span>(GeneralHealth_by<span class="sc">$</span>count[<span class="dv">7</span><span class="sc">:</span><span class="dv">9</span>])<span class="sc">/</span><span class="fu">sum</span>(GeneralHealth_by<span class="sc">$</span>count[<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>]) </span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>YesDiabetes_fourth <span class="ot">&lt;-</span> GeneralHealth_by<span class="sc">$</span>count[<span class="dv">10</span>]<span class="sc">/</span><span class="fu">sum</span>(GeneralHealth_by<span class="sc">$</span>count[<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>])</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"GeneralHealth 1 through 3, HasDiabetes in 'No'"</span><span class="ot">=</span>NoDiabetes_high_three, <span class="st">"GeneralHealth 4, HasDiabetes in 'No'"</span><span class="ot">=</span>NoDiabetes_fourth, <span class="st">"GeneralHealth 2 through 4, HasDiabetes in 'Yes'"</span><span class="ot">=</span>YesDiabetes_high_three, <span class="st">"GeneralHealth 5, HasDiabetes in 'Yes'"</span><span class="ot">=</span>NoDiabetes_fourth))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`GeneralHealth 1 through 3, HasDiabetes in 'No'`
[1] 0.8674027

$`GeneralHealth 4, HasDiabetes in 'No'`
[1] 0.09865936

$`GeneralHealth 2 through 4, HasDiabetes in 'Yes'`
[1] 0.8406513

$`GeneralHealth 5, HasDiabetes in 'Yes'`
[1] 0.09865936</code></pre>
</div>
</div>
<p>Review of the <strong>GeneralHealth</strong> response proportions in the “No” <strong>HasDiabetes</strong> group shows that over 86.59% of the observations reported having a <strong>GeneralHealth</strong> status of “Good” or better for the three highest responses with the 4th highest response of “Fair” accounting for another 9.98% of group responses. Review of the <strong>GeneralHealth</strong> response proportions in the “Yes” <strong>HasDiabetes</strong> shows that over 83.82% of the observations reported having a <strong>GeneralHealth</strong> status of “Very Good” to “Fair” for the three highest responses with the fourth highest response of “Poor” accounting for another 9.98% of group responses. The shift in <strong>GeneralHealth</strong> tendency between the <strong>HasDiabetes</strong> groups suggests that there is a relationship between the variables. <strong>GeneralHealth</strong> appears to be a suitable variable for prediciton modeling.</p>
<p>The next variable we’re going to summarize is <strong>BadMentalHealth</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of BadMentalHealth"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>BadMentalHealth)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of BadMentalHealth`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   0.000   3.155   2.000  30.000 </code></pre>
</div>
</div>
<p>shows that there is a tendency for the PTs to report that their mental health was not good for zero days.</p>
<p>Review of a histogram of the variable along with histograms of <strong>MentalHealth</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>BadMentalHealth_histogram <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes_df, <span class="fu">aes</span>(BadMentalHealth)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth=</span><span class="dv">1</span>, <span class="at">fill=</span><span class="st">"#CC0000"</span>, <span class="at">color=</span><span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Histogram of BadMentalHealth"</span>, <span class="at">x=</span><span class="st">"# of Days Mental Health Not Good"</span>, <span class="at">y=</span><span class="st">"Density (# of PTs)"</span>)</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>BadMentalHealth_histogram</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>BadMentalHealth_by_histplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes_df, <span class="fu">aes</span>(BadMentalHealth)) <span class="sc">+</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth=</span><span class="dv">1</span>, <span class="at">fill=</span><span class="st">"#CC0000"</span>, <span class="at">color=</span><span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Histogram of BadMentalHealth by HasDiabetes"</span>, <span class="at">y=</span><span class="st">"Density (# of PTs)"</span>) <span class="sc">+</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>HasDiabetes)</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>BadMentalHealth_by_histplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the majority of the observations in both categories of <strong>HasDiabetes</strong> follow the similar trend where the majority of non-zero values in <strong>BadMentalHealth</strong> are in the range of 1-10 days. After remvoing the zero values for analysis, we compared the proportions of 10-day <strong>BadMentalHealth</strong> ranges between the <strong>HasDiabetes</strong> groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>BadMentalHealth_by_nozero <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, BadMentalHealth) <span class="sc">|&gt;</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(BadMentalHealth <span class="sc">&gt;=</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(BadMentalHealth_by_nozero, <span class="at">n=</span><span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 3
# Groups:   HasDiabetes [2]
   HasDiabetes BadMentalHealth count
   &lt;fct&gt;                 &lt;dbl&gt; &lt;int&gt;
 1 0                         1  7679
 2 0                         2 11465
 3 0                         3  6403
 4 0                         4  3259
 5 0                         5  7729
 6 0                         6   819
 7 0                         7  2672
 8 0                         8   524
 9 0                         9    78
10 0                        10  5256
11 0                        11    38
12 0                        12   330
13 0                        13    32
14 0                        14   957
15 0                        15  4422
16 0                        16    73
17 0                        17    42
18 0                        18    76
19 0                        19    12
20 0                        20  2654
21 0                        21   178
22 0                        22    50
23 0                        23    30
24 0                        24    27
25 0                        25   896
26 0                        26    37
27 0                        27    66
28 0                        28   268
29 0                        29   128
30 0                        30  9183
31 1                         1   788
32 1                         2  1481
33 1                         3   900
34 1                         4   476
35 1                         5  1186
36 1                         6   158
37 1                         7   391
38 1                         8   106
39 1                         9    12
40 1                        10  1033
41 1                        11     3
42 1                        12    62
43 1                        13     8
44 1                        14   190
45 1                        15   989
46 1                        16    12
47 1                        17    11
48 1                        18    19
49 1                        19     4
50 1                        20   639
51 1                        21    46
52 1                        22    10
53 1                        23     8
54 1                        24     6
55 1                        25   258
56 1                        26     6
57 1                        27    11
58 1                        28    54
59 1                        29    27
60 1                        30  2664</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>HasDiabetesNo_first_ten <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"HasDiabetesNo, BadMentalHealth, 1-10 days proprotion of data"</span> <span class="ot">=</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>])<span class="sc">/</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>]))</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>HasDiabetesNo_middle_ten <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"HasDiabetesNo, BadMentalHealth, 11-20 days proprotion of data"</span> <span class="ot">=</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">11</span><span class="sc">:</span><span class="dv">20</span>])<span class="sc">/</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>]))</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>HasDiabetesNo_last_ten <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"HasDiabetesNo, BadMentalHealth, 21-30 days proprotion of data"</span> <span class="ot">=</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">21</span><span class="sc">:</span><span class="dv">30</span>])<span class="sc">/</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>]))</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>HasDiabetesYes_first_ten <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"HasDiabetesYes, BadMentalHealth, 1-10 days proprotion of data"</span><span class="ot">=</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">31</span><span class="sc">:</span><span class="dv">40</span>])<span class="sc">/</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">31</span><span class="sc">:</span><span class="dv">60</span>]))</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>HasDiabetesYes_middle_ten <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"HasDiabetesYes, BadMentalHealth, 11-20 days proprotion of data"</span><span class="ot">=</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">41</span><span class="sc">:</span><span class="dv">50</span>])<span class="sc">/</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">31</span><span class="sc">:</span><span class="dv">60</span>]))</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>HasDiabetesYes_last_ten <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"HasDiabetesYes, BadMentalHealth, 20-30 days proprotion of data"</span><span class="ot">=</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">51</span><span class="sc">:</span><span class="dv">60</span>])<span class="sc">/</span><span class="fu">sum</span>(BadMentalHealth_by_nozero<span class="sc">$</span>count[<span class="dv">31</span><span class="sc">:</span><span class="dv">60</span>]))</span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(HasDiabetesNo_first_ten, HasDiabetesYes_first_ten, HasDiabetesNo_middle_ten, HasDiabetesYes_middle_ten, HasDiabetesNo_last_ten, HasDiabetesYes_last_ten))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`HasDiabetesNo, BadMentalHealth, 1-10 days proprotion of data`
[1] 0.7017726

$`HasDiabetesYes, BadMentalHealth, 1-10 days proprotion of data`
[1] 0.5650632

$`HasDiabetesNo, BadMentalHealth, 11-20 days proprotion of data`
[1] 0.1320833

$`HasDiabetesYes, BadMentalHealth, 11-20 days proprotion of data`
[1] 0.1675895

$`HasDiabetesNo, BadMentalHealth, 21-30 days proprotion of data`
[1] 0.1661441

$`HasDiabetesYes, BadMentalHealth, 20-30 days proprotion of data`
[1] 0.2673473</code></pre>
</div>
</div>
<p>The comparisons showed that the “No” <strong>HasDiabetes</strong> group had a 70% of their <strong>BadMentalHealth</strong> responses in the 1-10 day range while the “Yes” <strong>HasDiabetes</strong> group only had a 56.2% of their <strong>BadMentalHealth</strong> responses in the same range. Likewise, the “Yes” <strong>HasDiabetes</strong> group had higher percentages of responses in both the 11-20 day and 21-30 day <strong>BadMentalHealth</strong> ranges than the “No” <strong>HasDiabetes</strong> group. The change in “0” response density between the <strong>HasDiabetes</strong> groups appears to have shifted to longer periods of PTs with diabetes experiencing mental health that is not good. This shows that there is a relationship between the variables. <strong>BadMentalHealth</strong> appears to be suitable for prediction modeling.</p>
<p>The next variable we’re going to summarize is <strong>BadPhysicalHealth</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of PhysicalHealth"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>BadPhysicalHealth)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of PhysicalHealth`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   0.000   4.194   3.000  30.000 </code></pre>
</div>
</div>
<p>shows that like <strong>BadMentalHealth</strong>, the vast majority of <strong>BadPhysicalHealth</strong> responses provided were “0”. Reviewing a density plot histogram of <strong>BadPhysicalHealth</strong> along with histogram plots of <strong>BadPhysicalHealth</strong> with respect to <strong>HasDiabetes</strong> show</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>BadPhysicalHealth_histogram <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes_df, <span class="fu">aes</span>(BadPhysicalHealth)) <span class="sc">+</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth=</span><span class="dv">1</span>, <span class="at">fill=</span><span class="st">"#CC0000"</span>, <span class="at">color=</span><span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Histogram of BadPhysicalHealth"</span>, <span class="at">x=</span><span class="st">"# of Days Mental Health Not Good"</span>, <span class="at">y=</span><span class="st">"Density (# of PTs)"</span>)</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>BadPhysicalHealth_histogram</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>BadPhysicalHealth_by_histplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(diabetes_df, <span class="fu">aes</span>(BadPhysicalHealth)) <span class="sc">+</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth=</span><span class="dv">1</span>, <span class="at">fill=</span><span class="st">"#CC0000"</span>, <span class="at">color=</span><span class="st">"lightgray"</span>) <span class="sc">+</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Histogram of BadPhysicalHealth by HasDiabetes"</span>, <span class="at">y=</span><span class="st">"Density (# of PTs)"</span>) <span class="sc">+</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>HasDiabetes)</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>BadPhysicalHealth_by_histplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that like with <strong>BadMentalHealth</strong>, the density of the <strong>BadPhysicalHealth</strong> “0” response changes between the <strong>HasDiabetes</strong> groups. The general trend is that when compared to the “No” <strong>HasDiabetes</strong> group the “Yes” <strong>HasDiabetes</strong> densities in the 0-7 day range are lower and then overall higher among the remaining groups. Comparing the proportions of the 0-7day ranges to the 8-30 day ranges</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>BadPhysicalHealth_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, BadMentalHealth) <span class="sc">|&gt;</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>BadPhysHlth_DiabetesNo_firstSeven <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"BadPhysHealth 1-7 Days, Diabetes in 'No'"</span> <span class="ot">=</span> <span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])<span class="sc">/</span><span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">31</span>]))</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>BadPhysHlth_DiabetesNo_lastTwentyThree <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"BadPhysHealth 8-30 Days, Diabetes in 'No'"</span> <span class="ot">=</span> <span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">9</span><span class="sc">:</span><span class="dv">31</span>])<span class="sc">/</span><span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">31</span>]))</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>BadPhysHlth_DiabetesYes_firstSeven <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"BadPhysHealth 1-7 Days, Diabetes in 'Yes'"</span> <span class="ot">=</span> <span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">32</span><span class="sc">:</span><span class="dv">39</span>])<span class="sc">/</span><span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">32</span><span class="sc">:</span><span class="dv">62</span>]))</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>BadPhysHlth_DiabetesYes_lastTwentyThree <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"BadPhysHealth 8-30 Days, Diabetes in 'Yes'"</span> <span class="ot">=</span> <span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">40</span><span class="sc">:</span><span class="dv">62</span>])<span class="sc">/</span><span class="fu">sum</span>(BadPhysicalHealth_by<span class="sc">$</span>count[<span class="dv">32</span><span class="sc">:</span><span class="dv">62</span>]))</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(BadPhysHlth_DiabetesNo_firstSeven, BadPhysHlth_DiabetesYes_firstSeven, BadPhysHlth_DiabetesNo_lastTwentyThree, BadPhysHlth_DiabetesYes_lastTwentyThree))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`BadPhysHealth 1-7 Days, Diabetes in 'No'`
[1] 0.8830596

$`BadPhysHealth 1-7 Days, Diabetes in 'Yes'`
[1] 0.8216564

$`BadPhysHealth 8-30 Days, Diabetes in 'No'`
[1] 0.1169404

$`BadPhysHealth 8-30 Days, Diabetes in 'Yes'`
[1] 0.1783436</code></pre>
</div>
</div>
<p>confirms that the visual assessments are correct. The “No” <strong>HasDiabetes</strong> group is 6.4 percentage points higher in the <strong>BadPhysicalHealth</strong> 0-7 day range compared to the “Yes” <strong>HasDiabetes</strong> group. This change in <strong>HasDiabetes</strong> suggests that there is a relationship between the variables. **BadPhysicalHealth* appears to be suitable for prediction modeling.</p>
<p>The next variable we’re going to summarize is <strong>DifficultyWalking</strong>. Reviewing the variable summary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of DifficultyWalking"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>DifficultyWalking)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of DifficultyWalking`
     0      1 
209904  41574 </code></pre>
</div>
</div>
<p>shows that the majority of PTs reported “No” at a ratio of approximately 211:43, which reduces to slightly less than 5:1. This suggests that any differences in the <strong>HasDiabetes</strong> groups will be highly influenced by the number of PTs in each. Reviewing the bar plot of <strong>DifficultyWalking</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>DifficultyWalking_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, DifficultyWalking) <span class="sc">|&gt;</span></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>DifficultyWalking_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(DifficultyWalking_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>DifficultyWalking)) <span class="sc">+</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of DifficultyWalking by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a>DifficultyWalking_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the majority of responses in both <strong>HasDiabetes</strong> groups fall under the “No” <strong>DifficultyWalking</strong> group. The observations in the “No” <strong>HasDiabetes</strong> category have a “No” to “Yes” <strong>DifficultyWalking</strong> ratio of approximately 188:30 which simplifies down to a ratio slightly greater than 6:1. The observations in the “Yes” <strong>HasDiabetes</strong> category have a “No” to “Yes” <strong>DifficultyWalking</strong> ratio of approximately 222:131 which simplifies down to closer to 2:1 than 1:1. The change in ratios suggests that there is a relationship between the variabels. However, the relationship appears to be one where someone having diabetes or not can help predict if they’ll have difficulty walking, but that is not what we’re trying to predict. <strong>DifficultyWalking</strong> does not appear to be a suitable variable for our prediction model.</p>
<p>The next variable we’re going to summarize is <strong>Sex</strong>. Reviewing the variable summary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Sex"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>Sex)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Sex`
     0      1 
140542 110936 </code></pre>
</div>
</div>
<p>shows that the distribution between the categories is almost uniform at a female to male ratio of approximately 142:111 which simplifies to a ratio slightly greater than 1:1. Reviewing the bar plot of <strong>Sex</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>Sex_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, Sex) <span class="sc">|&gt;</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>Sex_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Sex_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>Sex)) <span class="sc">+</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>()) <span class="sc">+</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of Sex by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) </span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>Sex_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that the number of females is greater in both <strong>HasDiabetes</strong> groups. The observations in the “No” <strong>HasDiabetes</strong> category have a “No” to “Yes” <strong>Sex</strong> ratio of approximately 124:95 which simplifies down to a ratio of slightly greater than 1:1. The observations in the “Yes” <strong>HasDiabetes</strong> category have a “No” to “Yes” <strong>Sex</strong> ratio of approximately 184:169 which also simplifies down to a ratio slightly greater than 1:1. The difference between the groups is minimal which suggests there is not a relationship between the variables. <strong>Sex</strong> does not appear suitable for our prediciton model.</p>
<p>The next variable we’re going to summarize is <strong>Age</strong>. Review of the variable summary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Age"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>Age)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Age`
    1     2     3     4     5     6     7     8     9    10    11    12    13 
 5659  7506 10947 13680 15963 19569 26002 30503 32959 31963 23451 15942 17334 </code></pre>
</div>
</div>
<p>shows that there is a trend where the number of responses increase in each category until group 9 (60-64), where they then decrease as from category 10 to 12 with group 13 being slightly higher than group 12. Reviewing histograms of <strong>Age</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>Age_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, Age) <span class="sc">|&gt;</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>Age_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Age_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>Age)) <span class="sc">+</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge2</span>()) <span class="sc">+</span></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of Age by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>)</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>Age_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that there a shift in distribution between the <strong>HasDiabetes</strong> groups. The “No” <strong>HasDiabetes</strong> group has central tendency around resonse “9” while the “Yes” <strong>HasDiabetes</strong> group has a central tendency around response “10”. Review of a summary table of the proportions between the <strong>HasDiabetes</strong> categories by groups shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>AgeGrp <span class="ot">&lt;-</span> Age_by<span class="sc">$</span>Age[<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>]</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>proportionNo <span class="ot">&lt;-</span> <span class="fu">proportions</span>(Age_by<span class="sc">$</span>count[<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>])</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>proporitonYes <span class="ot">&lt;-</span><span class="fu">proportions</span>(Age_by<span class="sc">$</span>count[<span class="dv">14</span><span class="sc">:</span><span class="dv">26</span>])</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>Age_Diabetes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(AgeGrp, proportionNo, proporitonYes)</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>Age_Diabetes <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(Age_Diabetes)</span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary Table of Age Proportions"</span><span class="ot">=</span>Age_Diabetes))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary Table of Age Proportions`
# A tibble: 13 × 3
   AgeGrp proportionNo proporitonYes
   &lt;fct&gt;         &lt;dbl&gt;         &lt;dbl&gt;
 1 1            0.0257       0.00219
 2 2            0.0340       0.00367
 3 3            0.0491       0.00849
 4 4            0.0603       0.0172 
 5 5            0.0690       0.0288 
 6 6            0.0825       0.0482 
 7 7            0.106        0.0860 
 8 8            0.122        0.120  
 9 9            0.126        0.162  
10 10           0.118        0.186  
11 11           0.0846       0.147  
12 12           0.0579       0.0979 
13 13           0.0652       0.0923 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>proportionNo_largestThree <span class="ot">&lt;-</span> <span class="fu">sum</span>(Age_Diabetes<span class="sc">$</span>proportionNo[<span class="dv">8</span><span class="sc">:</span><span class="dv">10</span>])</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>proportionYes_largestThree <span class="ot">&lt;-</span> <span class="fu">sum</span>(Age_Diabetes<span class="sc">$</span>proporitonYes[<span class="dv">9</span><span class="sc">:</span><span class="dv">11</span>])</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Cummulative Proportion of 3 largest Age groups, HasDiabetes - No"</span><span class="ot">=</span>proportionNo_largestThree, <span class="st">"Cummulative Proportion of 3 largest Age groups, HasDiabetes - Yes"</span><span class="ot">=</span>proportionYes_largestThree))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Cummulative Proportion of 3 largest Age groups, HasDiabetes - No`
[1] 0.3653251

$`Cummulative Proportion of 3 largest Age groups, HasDiabetes - Yes`
[1] 0.4956554</code></pre>
</div>
</div>
<p>that not only did the distributions shift between the age groups, but the highest three <strong>Age</strong> categories (8-10) in the “No” <strong>HasDiabetes</strong> group account for 36.51% of the group data while the highest three <strong>Age</strong> categories (9-11) in the “Yes” <strong>HasDiabetes</strong> category account for 49.32% of the group data. These shifts in proportions suggest that there is a relationship between the variables. <strong>Age</strong> appears to be suitable for prediction modeling.</p>
<p>The next variabel we’re going to summarize is <strong>Education</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Education"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>Education)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Education`
     1      2      3      4      5      6 
   170   3975   9342  62130  69218 106643 </code></pre>
</div>
</div>
<p>shows that the responses increased in each category with the majority of observations belonging to category 6 (College 4yrs or more (College graduate)). Reviewing the bar plot of <strong>Education</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>Education_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, Education) <span class="sc">|&gt;</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>Education_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Education_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>Education)) <span class="sc">+</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge2</span>()) <span class="sc">+</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">hjust=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of Education by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>) <span class="sc">+</span></span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a>Education_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>shows that there is a definite change in the ratios of the <strong>Education</strong> gropus between the <strong>HasDiabetes</strong> groups. The “No” <strong>HasDiabetes</strong> group follows the same trend as the overall data while the “Yes” <strong>HasDiabetes</strong> group has a fairly uniform distribution between categories 4, 5, and 6. There does appear to be a relationship between the variables where we could determine there was a high probability that someone with diabetes has a high probability of having a high school diploma, GED, or higher education but the data does not lend itself to determining if a given education level can be used to predict if someone has diabetes. <strong>Education</strong> does not appear to be suitable for prediction analysis.</p>
<p>The last variable that we’re going to summarize is <strong>Income</strong>. Review of the variable summary information</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">list</span>(<span class="st">"Summary of Income"</span><span class="ot">=</span><span class="fu">summary</span>(diabetes_df<span class="sc">$</span>Income)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`Summary of Income`
    1     2     3     4     5     6     7     8 
 9598 11542 15780 19882 25635 36184 42907 89950 </code></pre>
</div>
</div>
<p>shows that the number of responses increase as the categories increase, with the largest group earning $75K per year or more. Reviewing a bar plot of <strong>Income</strong> with respect to <strong>HasDiabetes</strong> shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>Income_by <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(HasDiabetes, Income) <span class="sc">|&gt;</span></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'HasDiabetes'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>Income_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Income_by, <span class="fu">aes</span>(HasDiabetes, count, <span class="at">fill=</span>Income)) <span class="sc">+</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge2</span>()) <span class="sc">+</span></span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.25</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb132-5"><a href="#cb132-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Bar Plot of Income by HasDiabetes"</span>, <span class="at">x=</span><span class="st">"Has Diabetes"</span>, <span class="at">y=</span> <span class="st">"# of PTs"</span>)</span>
<span id="cb132-6"><a href="#cb132-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-7"><a href="#cb132-7" aria-hidden="true" tabindex="-1"></a>Income_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>that there is a shift in proportions of <strong>Income</strong> group categories between the <strong>HasDiabetes</strong> groups. The <strong>Income</strong> groups with “No” <strong>HasDiabetes</strong> responses appear to have a quadratic relationship with a large positive slope between groups 7 and 8. The <strong>Income</strong> groups with “Yes” <strong>HasDiabetes</strong> responses appear to have a linear relationship with a small positive slope. There appears to be a relationship between the variables where a person with diabetes has a greater probability of earning less than $75K pe year, but that is not what we’re trying to predict. <strong>Income</strong> does not appear to be suitable for prediction modeling.</p>
<p>Now that we have identified the variables with relationships to <strong>HasDiabetes</strong>, we will consider if they are independent from one another. Review of a heat plot of <strong>HasDiabetes</strong> compared to the six predictor variables shows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>diabetes_df_model <span class="ot">&lt;-</span> diabetes_df <span class="sc">|&gt;</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(HasDiabetes, HighCholesterol, BMI, GeneralHealth, BadMentalHealth, BadPhysicalHealth, Age) </span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>independenceCheck <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span>., </span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">data=</span>diabetes_df_model) <span class="sc">|&gt;</span></span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>) <span class="sc">|&gt;</span></span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggcorrplot</span>(<span class="at">title=</span><span class="st">"Heat Plot of Predictor Variable Correlations"</span>, <span class="at">show.diag=</span><span class="cn">FALSE</span>, <span class="at">type=</span><span class="st">"lower"</span>, <span class="at">lab=</span><span class="cn">TRUE</span>, <span class="at">lab_size=</span><span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>),</span>
<span id="cb133-9"><a href="#cb133-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(model.matrix(~., data = diabetes_df_model), use =
"pairwise.complete.obs"): the standard deviation is zero</code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(independenceCheck)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProjectEDA_files/figure-html/generate correlation matrix-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>there are notable interactions between <strong>GeneralHealth</strong>, <strong>BadMentalHealth</strong>, and <strong>BadPhysicalHealth</strong>.</p>
<p>As <strong>GeneralHealth</strong> approaches category 5, the value of the correlation coefficient between it and <strong>BadPhysicalHealth</strong> increases to a moderate degree of correlation with maximum value of 0.49. <strong>GeneralHealth</strong> categories 2 through 4 all have weak correlation coefficients with <strong>BadPhysicalHealth</strong> ranging from -0.23 to 0.31.</p>
<p>As <strong>GeneralHealth</strong> approaches category 5, the value of the correlation coefficient between it and <strong>BadMentalHealth</strong> increases to a weak degree of correlation with maximum value of 0.26. <strong>GeneralHealth</strong> categories 2 through 4 also have weak correlation coefficients with <strong>BadMentalHealth</strong> ranging from -0.13 to 0.17.</p>
<p><strong>BadMentalHealth</strong> and <strong>BadPhysicalHealth</strong> have a moderate degree of correlation with a correlation coefficient of 0.35.</p>
<p>Because <strong>BadPhysicalHealth</strong> greatly influences both <strong>GeneralHealth</strong> and <strong>BadMentalHealth</strong>, because <strong>BadMentalHealth</strong> also influences <strong>GeneralHealth</strong>, and because <strong>BadPhysicalHealth</strong> has the highest correlation coefficient with <strong>HasDiabetes</strong>, it would be reasonable to remove <strong>GeneralHealth</strong> and <strong>BadMentalHealth</strong> from being used as predictor variables due to their dependence on <strong>BadPhysicalHealth</strong>.</p>
<p>The remaining combinations of variable groups all have weak correlation coefficients in the -0.30 to 0.30 range. Each of these variables appear to be independent from one another.</p>
<p>Now that we have completed our EDA, we will use the above information in our <a href="https://jpatt1980.github.io/FinalProject/FinalProjectModeling.html">Final Project Modeling</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>